#!/usr/bin/env python3
"""Expand B1 Units 9-12 with more Quebec French content."""

def read_file(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()

def write_file(path, content):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)

def insert_before(html, marker, new_content):
    idx = html.find(marker)
    if idx == -1:
        print(f"WARNING: marker not found: {marker[:80]}...")
        return html
    return html[:idx] + new_content + html[idx:]

def main():
    path = r'e:\MyProjects\Web\Jason-French-Learning-Web\b1.html'
    html = read_file(path)

    # =========================================================================
    # UNIT 9: MEDIA & NEWS
    # =========================================================================
    marker_9_end = '<h2 id="h-b1-u10">'
    new_9 = """
<p><strong>The Quebec Media Landscape (🍁):</strong></p>
<p>Understanding the local media is key to cultural integration.</p>
<table>
<thead><tr><th>Media Outlet</th><th>Type</th><th>Reputation/Focus</th></tr></thead>
<tbody>
<tr><td><strong>ICI Radio-Canada</strong></td><td>Public Broadcaster (TV/Radio)</td><td>National news, highly neutral, standard French reference. Includes ICI Tou.tv (streaming).</td></tr>
<tr><td><strong>TVA / Le Journal de Montréal</strong></td><td>Private Network / Tabloid</td><td>Populist, crime coverage ("faits divers"), sports, heavy use of emotive headlines.</td></tr>
<tr><td><strong>La Presse</strong></td><td>Digital Newspaper (App)</td><td>Centrist, exhaustive journalism, excellent opinion pages (La Presse+).</td></tr>
<tr><td><strong>Le Devoir</strong></td><td>Print/Digital Newspaper</td><td>Intellectual, independent, slightly sovereignist/center-left, deep analysis.</td></tr>
<tr><td><strong>L'Actualité</strong></td><td>Monthly Magazine</td><td>High-quality investigative journalism and societal phenomena.</td></tr>
</tbody>
</table>

<p><strong>Journalism Vocabulary:</strong></p>
<ul>
<li><strong>La une:</strong> The front page. <em>Faire la une des journaux (To make the front page).</em></li>
<li><strong>Un chroniqueur / Une chroniqueuse:</strong> A columnist (very influential in Quebec media).</li>
<li><strong>Les faits divers:</strong> Local crime, accidents, minor news.</li>
<li><strong>Un sondage:</strong> A poll/survey (Léger Marketing is the most famous polling firm in QC).</li>
</ul>

<p><strong>🇫🇷 Real-Life Scene – Discussing the Morning News:</strong></p>
<p>"As-tu lu l'article de La Presse ce matin sur la crise du logement?"<br>"J'ai lu la clinique (chronique) de Patrick Lagacé, oui. Il a vraiment mis le doigt sur le bobo."<br>"C'est incroyable. Selon les derniers sondages, plus de 60% des locataires à Montréal ont du mal à boucler leurs fins de mois."<br>"J'écoutais Radio-Canada Première en venant travailler, et ils disaient la même chose. Le présentateur interviewait la ministre responsable de l'Habitation."</p>

"""
    html = insert_before(html, marker_9_end, new_9)

    # =========================================================================
    # UNIT 10: ENVIRONMENT
    # =========================================================================
    marker_10_end = '<h2 id="h-b1-u11">'
    new_10 = """
<p><strong>Quebec and the Environment: Hydro-Québec & Winters (🍁):</strong></p>
<p>Quebec prides itself on being a leader in green energy thanks to <strong>Hydro-Québec</strong>.</p>
<ul>
<li><strong>L'hydroélectricité:</strong> 99% of electricity in Quebec is renewable, generated by massive dams (barrages) in Northern Quebec (like the Complexe La Grande, Baie-James).</li>
<li><strong>Le réchauffement climatique:</strong> Climate change in Quebec means milder but more erratic winters. You will hear about <em>"le verglas"</em> (freezing rain) destroying power lines, and changing seasons affecting the <em>"saison des sucres"</em> (maple syrup season).</li>
</ul>

<p><strong>Green Living Vocabulary:</strong></p>
<ul>
<li><strong>Le recyclage et le compostage:</strong> Most municipalities have the "bac bleu" (blue bin for recycling), "bac brun" (brown bin for compost), and "bac noir/vert" (garbage).</li>
<li><strong>Une éolienne:</strong> A wind turbine (often seen in the Gaspésie region).</li>
<li><strong>L'empreinte carbone:</strong> Carbon footprint.</li>
<li><strong>Écoresponsable:</strong> Eco-friendly.</li>
</ul>

<p><strong>🇫🇷 Real-Life Scene – Sorting the Trash:</strong></p>
<p>"Hey, tu ne peux pas jeter cette boîte de pizza dans le bac noir!"<br>"Ah non? La boîte est sale, je pensais que ça n'allait pas au recyclage."<br>"Ça ne va pas au recyclage, ça va dans le bac brun pour le compostage!"<br>"C'est compliqué de trier ses déchets ici... et les bouteilles de bière?"<br>"Les bouteilles sont consignées. On les rapporte à l'épicerie ou au dépanneur pour récupérer la consigne de 10 sous."</p>

"""
    html = insert_before(html, marker_10_end, new_10)

    # =========================================================================
    # UNIT 11: WORK & CAREER
    # =========================================================================
    marker_11_end = '<h2 id="h-b1-u12">'
    new_11 = """
<p><strong>The Quebec Job Market & CV Standards (🍁):</strong></p>
<p>When searching for a job in Quebec, there are strict standards that differ from Europe and the US:</p>
<ul>
<li><strong>Le CV québécois:</strong> No photo, no date of birth, no marital status (illegal discrimination). It can be 2 pages long.</li>
<li><strong>L'entrevue d'embauche:</strong> Tends to be less formal, focusing on "fit" and "savoir-être" (soft skills) as much as technical skills ("savoir-faire").</li>
<li><strong>Le réseautage:</strong> Networking on LinkedIn or at "5 à 7" events is critical. The "marché caché" (hidden job market) is huge here.</li>
<li><strong>Le bilinguisme:</strong> Many jobs in Montreal require both French and English ("Parfaitement bilingue, tant à l'oral qu'à l'écrit").</li>
</ul>

<p><strong>Key Job Search Vocabulary:</strong></p>
<ul>
<li><strong>Un poste à temps plein / à temps partiel:</strong> A full-time / part-time position.</li>
<li><strong>Une mise à pied:</strong> A lay-off. <em>"L'usine a annoncé 100 mises à pied."</em></li>
<li><strong>Les avantages sociaux (QC):</strong> Fringe benefits (health insurance, dental, retirement). <em>Note: In France, this means welfare, but in QC it means job perks!</em></li>
<li><strong>Le télétravail:</strong> Working from home / remote work.</li>
</ul>

<p><strong>🇫🇷 Real-Life Scene – A Job Interview:</strong></p>
<p>"Bonjour, bienvenue chez Ubisoft Montréal. Prenez place."<br>"Merci beaucoup de me recevoir."<br>"Pour commencer, parlez-moi un peu de votre parcours. J'ai vu sur votre CV que vous avez travaillé à Paris."<br>"Oui, j'ai été développeur logiciel pendant trois ans. Mais je cherchais un nouveau défi professionnel, c'est pourquoi j'ai décidé d'immigrer au Québec."<br>"Excellent. Ici, le travail d'équipe est primordial. Comment gérez-vous la pression quand la date de livraison (deadline) approche?"<br>"Je reste organisé et je communique de façon proactive avec mon équipe pour éviter les goulots d'étranglement."<br>"C'est parfait. Avez-vous des questions sur les avantages sociaux de l'entreprise?"</p>

"""
    html = insert_before(html, marker_11_end, new_11)

    # =========================================================================
    # UNIT 12: EDUCATION
    # =========================================================================
    marker_12_end = '<h1 id="h-b1-part-iv">'
    new_12 = """
<p><strong>The Quebec Education System (🍁):</strong></p>
<p>Quebec has a highly distinct education system compared to the rest of Canada and France.</p>
<table>
<thead><tr><th>Level</th><th>Years/Ages</th><th>Equivalence / Details</th></tr></thead>
<tbody>
<tr><td><strong>Primaire</strong></td><td>6 years (Ages 6-12)</td><td>Elementary school.</td></tr>
<tr><td><strong>Secondaire</strong></td><td>5 years (Sec 1 to Sec 5) (Ages 12-17)</td><td>High school. Ends one year earlier than the rest of Canada.</td></tr>
<tr><td><strong>Cégep (Collégial)</strong></td><td>2 to 3 years (Ages 17-19+)</td><td><strong>Unique to Quebec.</strong> A bridge between high school and university. Pre-university (2 yrs) or Technical/Vocational (3 yrs).</td></tr>
<tr><td><strong>Université</strong></td><td>3 to 4 years (Ages 19+)</td><td>Bachelor's (Baccalauréat), Master's (Maîtrise), Doctorate (Doctorat).</td></tr>
</tbody>
</table>

<p><strong>Common Education Terms:</strong></p>
<ul>
<li><strong>La relâche:</strong> The spring break (usually first week of March).</li>
<li><strong>Les prêts et bourses:</strong> Student loans and grants from the government (AFE).</li>
<li><strong>L'UQAM, UdeM, McGill, Concordia, Laval, Sherbrooke:</strong> Major universities in the province.</li>
<li><strong>Couler un examen (QC):</strong> To fail an exam. (Equivalent to "échouer" or "rater").</li>
</ul>

<p><strong>🇫🇷 Real-Life Scene – Discussing CEGEP Applications:</strong></p>
<p>"Est-ce que ta fille a fait ses demandes d'admission pour l'année prochaine?"<br>"Oui, elle a fait sa demande au Cégep de Maisonneuve et au Cégep du Vieux Montréal."<br>"Ah oui! Dans quel programme?"<br>"Elle veut aller en Sciences humaines ou en Arts, lettres et communication. Elle n'est pas encore certaine de ce qu'elle veut faire à l'université."<br>"C'est l'avantage du cégep, ça lui donne deux ans pour y penser avant le baccalauréat!"<br>"Exactement. Mais elle doit réussir ses cours de français et de philo, c'est obligatoire pour obtenir son DEC (Diplôme d'études collégiales)."</p>

"""
    html = insert_before(html, marker_12_end, new_12)

    write_file(path, html)
    print("B1 Part 3 done: Units 9-12 expanded successfully!")

if __name__ == '__main__':
    main()
